DATA = {
    "dashboard": {
        "customer_name": "Priya",
        "financial_health_score": 82,
        "cards": [
            {"label": "Savings", "value": "₹42,000"},
            {"label": "Debt", "value": "18%"},
            {"label": "Insurance", "value": "72%"},
            {"label": "Liquidity", "value": "12 days"},
            {"label": "Investment Readiness", "value": "High"},
            {"label": "Emergency Fund", "value": "₹18,500"},
        ],
        "recent_recommendations": [
            "Build Emergency Fund",
            "Start SIP Ladder",
            "Review Insurance Cover",
        ],
        "upcoming_goals": [
            "Emergency corpus by September",
            "SIP review in 14 days",
            "Health insurance renewal",
        ],
    },
    "customer": {
        "name": "Priya Sharma",
        "age": 29,
        "occupation": "Product Manager",
        "life_stage": "Early career, urban renter",
        "risk_appetite": "Moderate",
        "savings_habit": "Consistent",
        "insurance": "Partial coverage",
        "goals": ["Emergency fund", "SIP", "Home down payment"],
        "financial_confidence": 74,
    },
    "financial_health": {
        "score": 82,
        "metrics": {
            "emergency_fund": "12 days",
            "savings_rate": "22%",
            "debt_ratio": "18%",
            "insurance_coverage": "72%",
            "investment_readiness": "High",
        },
        "monthly_health_score": [
            {"month": "Jan", "score": 68},
            {"month": "Feb", "score": 71},
            {"month": "Mar", "score": 74},
            {"month": "Apr", "score": 78},
            {"month": "May", "score": 80},
            {"month": "Jun", "score": 82},
        ],
        "savings_trend": [
            {"month": "Jan", "savings": 18000},
            {"month": "Feb", "savings": 22000},
            {"month": "Mar", "savings": 26000},
            {"month": "Apr", "savings": 31000},
            {"month": "May", "savings": 36000},
            {"month": "Jun", "savings": 42000},
        ],
    },
    "recommendation": {
        "title": "Build Emergency Fund",
        "confidence": 96,
        "priority": "High",
        "reason": "Emergency fund covers only 12 days.",
        "action": "Create AutoSave",
        "requires_customer_consent": True,
    },
    "timeline": [
        "Student",
        "First Salary",
        "Emergency Fund",
        "Recurring Deposit",
        "SIP",
        "Home Loan",
        "Retirement",
    ],
    "events": [
        "Salary Credited",
        "Financial Health Updated",
        "AI Triggered",
        "Reasoning Complete",
        "Recommendation Generated",
        "Awaiting Approval",
    ],
    "executive_dashboard": {
        "customers_assisted": "2.84M",
        "recommendations_generated": "7.2M",
        "financial_health_improvement": "14.8%",
        "digital_adoption": "68%",
        "customer_trust_score": "91/100",
        "support_tickets_reduced": "24%",
        "trend": [
            {"day": "Mon", "assisted": 1240, "approved": 820},
            {"day": "Tue", "assisted": 1510, "approved": 970},
            {"day": "Wed", "assisted": 1880, "approved": 1210},
            {"day": "Thu", "assisted": 2160, "approved": 1440},
            {"day": "Fri", "assisted": 2620, "approved": 1790},
            {"day": "Sat", "assisted": 2840, "approved": 1900},
        ],
    },
}
